### ISSUE TITLE
0.7 compat: Base.array_eltype_show_how

### ISSUE THREAD

**Issue by oyamad** [JuliaPolyhedra/Polyhedra.jl#112]
Just a reminder: `Base.array_eltype_show_how` no longer exists in 0.7:

https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/b915c05123a563cb25a3f02ffdaf4510f34c194d/src/show.jl#L11

Removed by https://github.com/JuliaLang/julia/commit/fe6709bfdfaf6650a2a62d13da38378e4b3c1710

**Comment by blegat** [comment]
Resolved in https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/120
