### ISSUE TITLE
UndefVarError with `default_library(d::FullDim, ::Type{T})`

### ISSUE THREAD

**Issue by oyamad** [JuliaPolyhedra/Polyhedra.jl#118]
#116 having been merged, `default_library(d::FullDim, ::Type{T})` now raises an error, despite what the documentation says:
https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/209d7d3fbb01d52f5f65078c3989e0a44020957b/src/default.jl#L24-L28

```jl
using Polyhedra
A = [1. 1; 1 -1; -1 0]
b = [1, 0, 0]
rep = hrep(A, b)
plib = default_library(FullDim{2}(), Float64)
```

```
ERROR: UndefVarError: FullDim not defined
```

**Comment by blegat** [comment]
FullDim has now a different definition, it is `Union{Int, StaticArrays.Size}`.
Here you should just do
```julia
plib = default_library(2, Float64)
```
