### ISSUE TITLE
CDDLibrary not defined error

### ISSUE THREAD

**Issue by arbenede** [JuliaPolyhedra/Polyhedra.jl#138]
I am getting this error under Windows 10 with Julia 1.0.2:

julia> hr = HalfSpace([1, 1], 1) ∩ HalfSpace([1, -1], 0) ∩ HalfSpace([-1, 0], 0)
H-representation Polyhedra.Intersection{Int64,Array{Int64,1},Int64}:
3-element iterator of HalfSpace{Int64,Array{Int64,1}}:
 HalfSpace([1, 1], 1)
 HalfSpace([1, -1], 0)
 HalfSpace([-1, 0], 0)

julia> using CDDLib

julia> polyf = polyhedron(hr, CDDLibrary())
ERROR: UndefVarError: CDDLibrary not defined
Stacktrace:
 [1] top-level scope at none:0

**Comment by oyamad** [comment]
@arbenede I guess you want to do

```jl
polyf = polyhedron(hr, CDDLib.Library())
```

@blegat The documentation should be updated ([search results](https://github.com/JuliaPolyhedra/Polyhedra.jl/search?q=CDDLibrary&unscoped_q=CDDLibrary)).

**Comment by arbenede** [comment]
Yes that works. Thank you @oyamad
