### ISSUE TITLE
Update convex hull example

### ISSUE THREAD

**Issue by mforets** [JuliaPolyhedra/Polyhedra.jl#142]
In the convex hull example of the [operations notebook](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/master/examples/operations.ipynb) one "checks" that the number of points in the convex hull is smaller than 30.

However, now `convexhull` does not remove the redundant vertices:

```julia
julia> P1 = polyhedron(vrep(randn(15, 2)), CDDLib.Library());

julia> P2 = polyhedron(vrep(randn(15, 2)), CDDLib.Library());

julia> Pch = convexhull(P1, P2);
julia> Pch
Polyhedron CDDLib.Polyhedron{Float64}:
30-element iterator of Array{Float64,1}:
 [-0.607654, 2.52052]
 [1.02428, -0.43121]
  ⋮
```

Should we add a call to `removevredundancy!` in the example notebook?

```julia
removevredundancy!(Pch)
julia> Pch
Polyhedron CDDLib.Polyhedron{Float64}:
7-element iterator of Array{Float64,1}:
 [-0.607654, 2.52052]
 ...
```

**Comment by blegat** [comment]
Yes, we could show that it still has 30 elements, add `removevredundancy!` and then show it again

**Comment by schillic** [comment]
But is this the intended behavior? I would expect that a convex hull is not just the union of the vertices.

**Comment by mforets** [comment]
> In the convex hull example of the operations notebook one "checks" that the number of points in the convex hull is smaller than 30.

It is not quite as i said, because the `P1` and `P2` in convex hull are the same as in intersection, and the call to `intersect(P1, P2)` reduces them. 

I've added a note with @blegat 's explanation in the end of the `operations` noteook in PR 
https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/144.
