### ISSUE TITLE
JuMP dependency issue

### ISSUE THREAD

**Issue by OliverEvans96** [JuliaPolyhedra/Polyhedra.jl#154]
Pkg3 seems to enforce JuMP <= 0.18 despite the specification of JuMP 0.16 - 0.19 in `REQUIRE`. This is probably related to updating from the old `REQUIRE`-style packaging to the new `Project.toml` style.

See [1] for a description of the specific problem and [2] for related discussion about the transition to Pkg3 style packaging.

[1]: https://discourse.julialang.org/t/metadata-vs-registry/21688/3
[2]: https://discourse.julialang.org/t/the-current-metadata-release-process/16672

**Comment by blegat** [comment]
`0.16 0.19` in REQUIRE excludes 0.19, it is the interval [0.16, 0.19[

**Comment by OliverEvans96** [comment]
Thank you!
