### ISSUE TITLE
Mesh displays with incorrect Material

### ISSUE THREAD

**Issue by ferrolho** [JuliaPolyhedra/Polyhedra.jl#180]
What it says in the title: seems that meshes created with Polyhedra.jl lack the correct material they are assigned, using MeshCat as the visualiser. The colour is correct, but Phong/Lambert does not result in the expected surface lighting.

```julia
v1 = [1 1 1 1 0 0 0 0
      1 1 0 0 1 1 0 0
      1 0 1 0 1 0 1 0.]'

p1 = polyhedron(vrep(v1), CDDLib.Library(:float))

m1 = Polyhedra.Mesh(p1)

material = MeshPhongMaterial(color=RGBA(1, 1, 1, 1.0))

setobject!(vis[:m1], m1, material)
```

I did not dig down enough to understand whether this is an issue with Polyhedra.jl or something else in MeshCat.jl.

**Comment by blegat** [comment]
I would expect it is an issue with MeshCat as Polyhedra only implements the GeometryTypes decompose API

cc @rdeits @tkoolen

**Comment by tkoolen** [comment]
Yeah, I don't see how this could be a Polyhedra issue. @ferrolho, feel free to open an issue with MeshCat, but FWIW I do see a slight difference between `MeshLambertMaterial` and `MeshPhongMaterial`, and I see the same difference between the two material types for a `GeometryTypes.HyperRectangle` of the same dimensions. You might want to experiment with some of the different `MeshPhongMaterial` options, see https://threejs.org/docs/index.html#api/en/materials/MeshPhongMaterial.

**Comment by ferrolho** [comment]
Closed in favour of https://github.com/rdeits/meshcat/issues/59.
