### ISSUE TITLE
polyhedron to array conversion?

### ISSUE THREAD

**Issue by henry2004y** [JuliaPolyhedra/Polyhedra.jl#189]
Hi,

I was trying to get the convex hull out of a set of 2D points. I followed the [example](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/master/examples/operations.ipynb) and saw the results, but is there a way to convert the `iterator of Array{Float64,1}` to an array type that I can manipulate?

Thanks!

**Comment by blegat** [comment]
You can call [`collect`](https://docs.julialang.org/en/v1/base/collections/#Base.collect-Tuple{Type,Any}).

**Comment by henry2004y** [comment]
Thanks!
