### ISSUE TITLE
no method matching `setobject!(::Visualizer, ::Polyhedra.Mesh)`

### ISSUE THREAD

**Issue by chriselrod** [JuliaPolyhedra/Polyhedra.jl#222]
I can't run any of the `MeshCat` examples, e.g. from the documentation:
https://juliapolyhedra.github.io/Polyhedra.jl/latest/plot/#D-plotting-with-Plots-2
or examples
https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/v0.6.7/examples/3D%20Plotting%20a%20projection%20of%20the%204D%20permutahedron.ipynb

```julia
using Polyhedra, MeshCat

v = convexhull([0,0,0]) + conichull([1,0,0], [0,1,0], [0,0,1])

p = polyhedron(v)

m = Polyhedra.Mesh(p)

vis = Visualizer()
setobject!(vis, m)
open(vis)
```

**Comment by blegat** [comment]
Can you try this branch https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/212 and see if it works?

**Comment by chriselrod** [comment]
It works.

**Comment by blegat** [comment]
Closed by https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/212
