### ISSUE TITLE
Why no lines/rays?

### ISSUE THREAD

**Issue by caseykneale** [JuliaPolyhedra/Polyhedra.jl#229]
Consider the following MWE:
```julia
using Polyhedra, CDDLib, JuMP

model = Model()

@variables(model, begin
    x
    y
end)

con = @constraints(model, begin 
    0. <= x <= 1.0
    0. <= y <= 1.0
    x <= y
end)

poly = polyhedron(model, CDDLib.Library(:exact))
points(vrep(poly))
```
We would expect a triangle to result. We get the points suggesting this is true, but if we look for lines/rays, there's nothing?
```julia
lines(vrep(poly))
```
Am I misunderstanding something - or is this an uh-oh for planar objects?

**Comment by mforets** [comment]
> We get the points suggesting this is true, but if we look for lines/rays, there's nothing?

The set has neither lines nor rays. It is bounded. Compare with the result obtained if you remove, for example, the first constraint.

**Comment by caseykneale** [comment]
I see. Is so this isn't an issue it's me not understanding what polyhedra is doing. I'll close this, not sure I know the correct way to go from a volume defined by constraints to a ray/line representation, but I'll keep thinking. 
Here's the related discourse thread: https://discourse.julialang.org/t/faces-vertices-of-n-linear-constraints/49347/7

**Comment by mforets** [comment]
> the correct way to go from a volume defined by constraints to a ray/line representation, but I'll keep thinking.

I think that you are interested in the facet enumeration problem? (see [Fukuda's Polyhedral Computation FAQ](https://www.cs.mcgill.ca/~fukuda/soft/polyfaq/node16.html) for additional context). I'm not sure if this library has algorithms for that problem out of-the-box.

Have in mind that vertex enumeration and facet enumeration are computationally hard problems. One can still work with sets in high dimensions using lazy set operations, restricting to specific classes of polyhedra such as zonotopes, and so on.
