### ISSUE TITLE
polyhedron(h) from docs causes infinite loop

### ISSUE THREAD

**Issue by PythonNut** [JuliaPolyhedra/Polyhedra.jl#230]
The following code runs "forever" on my system before being killed due to OOM.
```julia
using Polyhedra
h = HalfSpace([1, 1], 1) ∩ HalfSpace([-1, 0], 0) ∩ HalfSpace([0, -1], 0)
p = polyhedron(h)
```
Sending `SIGTERM` to `Julia` causes the following trace to be printed many times:
```
typeinf_edge at ./compiler/typeinfer.jl:484
abstract_call_method at ./compiler/abstractinterpretation.jl:419
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:111
abstract_call_known at ./compiler/abstractinterpretation.jl:904
abstract_call at ./compiler/abstractinterpretation.jl:926
abstract_call at ./compiler/abstractinterpretation.jl:911
abstract_eval at ./compiler/abstractinterpretation.jl:1005
typeinf_local at ./compiler/abstractinterpretation.jl:1270
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1326
typeinf at ./compiler/typeinfer.jl:12
```

* Polyhedra v0.6.8
* [Julia 1.5.2](https://aur.archlinux.org/packages/julia-bin/)
* OS: Arch Linux

**Comment by blegat** [comment]
This is due to printing, if you replace it with `polyhedron(h)`. I get the same thing and I am also o' ArchLinux. https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/216
Help is most welcome on this issue!

**Comment by blegat** [comment]
My current iterator is to avoid calling the itetators `halfspaces`, `points` either directly or indirectly (e.g. through printing) on polyhedra. You should first call `hrep` or `vrep` and use this instead.
Note that the time is compilation time so it seems to be a Julia bug.

**Comment by blegat** [comment]
See https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/216#issuecomment-1066128472
