### ISSUE TITLE
First time evaluation of polyhedron is still extremely slow

### ISSUE THREAD

**Issue by plut** [JuliaPolyhedra/Polyhedra.jl#237]
Using version `0.6.10` here, issue #110 still seems to be present. The symptoms are the exact same:
```julia
# the following lines are instantaneous:
using Polyhedra
A = [1. 1; 1 -1; -1 0]
b = [1, 0, 0]
rep = hrep(A, b)
plib = default_library(2, Float64) # <- slightly modified from #110
p=polyhedron(rep, plib);
# this line takes more than 5 minutes to run:
p
```

In #110 it is claimed that #122 fixed this. However, the problem might have re-appeared since then. As an alternative, using `GLPK` does not improve this much:
```julia
using GLPK
plib = Polyhedra.DefaultLibrary{Int64}(GLPK.Optimizer)
p=polyhedron(rep, plib);
p
```
produces the same results.

*edit* I also tried using `p = polyhedron(rep, CDDLib.Library())`, with the same result: the first call takes several minutes.

**Comment by mforets** [comment]
Hi,
I confirm that first time (printing) is still the same; which was reported here https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/216. Idk if this was reported upstream (I'm not familiar with rr, but perhaps it's worth a try.. ? Does the problem also happen with Julia v1.6 ?)

**Comment by blegat** [comment]
Indeed, this came back. I agree that reporting with `rr` could help Julia developers fix the compiler issue. But we should first check whether this is improved with Julia v1.6.

**Comment by mforets** [comment]
In Julia v1.6.0-beta1 the behavior is the same so I opened an issue (https://github.com/JuliaLang/julia/issues/39349).

**Comment by mforets** [comment]
In the meantime, starting Julia with `$ julia --compile-min` is a workaround, printing is immediate with that option (idk what other implications it has).

**Comment by blegat** [comment]
See https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/216#issuecomment-1066128472
