### ISSUE TITLE
Incorrect planar hull evaluation 

### ISSUE THREAD

**Issue by harshangrjn** [JuliaPolyhedra/Polyhedra.jl#271]
@blegat 
```julia
v = convexhull([0.0, 0.0], [1, 0], [0.5, 0.0], [-0.5, 0.0], [0.5, 0.5])
Polyhedra.planar_hull(v)
```
Output of the above evaluation is the extreme points (EPs) of the convex hull, which doesn't look right: 
```
 [0.0, 0.0]
 [0.5, 0.5]
 [1.0, 0.0]
```
But, if I simply re-order the original list of vertices to : 
```julia
v = convexhull([1, 0], [0.0, 0.0], [0.5, 0.0], [-0.5, 0.0], [0.5, 0.5])
```
I seem to get the correct EPs which is: 
```
 [1.0, 0.0]
 [-0.5, 0.0]
 [0.5, 0.5]
```
This is a bug, unless I am missing something in the input format.

**Comment by harshangrjn** [comment]
Is there an alternative option to evaluate the EPs of points in a plane?

**Comment by blegat** [comment]
Indeed, it looks incorrect. Here is a list of the alternatives: https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/master/examples/Convex%20hull%20of%20a%20set%20of%20points.jl

**Comment by harshangrjn** [comment]
The other option using `vrep` seems to lead to the same issue. Yet to try the CDDLib option.

**Comment by blegat** [comment]
Yes, `convexhull` and `vrep` won't change the behavior. CDDLib or QHull should work though.
