### ISSUE TITLE
Lots of time spent interpolating strings

### ISSUE THREAD

**Issue by plut** [JuliaPolyhedra/Polyhedra.jl#279]
When computing a somewhat small convex hull (215 vertices in total), I found (using `ProfileView`) that this package spends most of its time (roughly 95%!; I don't have the exact figure, only a flame graph...) interpolating the following string:

```julia
            if  is_feasible(model, "attempting to determine whether $element of index $idx is redundant.")
```
(`redundancy.jl` line 156). In that interpolation, the longest time is spent computing the text form of the data types...

The most obvious fix would be replacing the string by a lazy form (either by defining some `LogMessage` structure, or simply by passing a `Vector{Any}` and concatenating the strings thereof when needed).

**Comment by blegat** [comment]
I would be surprised if the string interpolation was the bottleneck. `is_feasible` ends up calling a linear programming solver:
https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/0288f2758e1e84f2896122b08a010febd0b6a2a2/src/opt.jl#L164
which is expected to be the bottleneck.

**Comment by plut** [comment]
Here is the relevant extract from `Profile.print()` showing that `_redundant_indices` spends about 90% of its time in `io.jl`.
```
  ╎    ╎    ╎    ╎    ╎    ╎    ╎   509 ...ndancy.jl:156; _redundant_indi...
 1╎    ╎    ╎    ╎    ╎    ╎    ╎    458 ...ngs/io.jl:174; string
````

**Comment by blegat** [comment]
Indeed, it seems to be in `io.jl`. Could you share the code of your example ?

**Comment by plut** [comment]
[Attached as a `.txt` file since github doesn't like `.jl` files](https://github.com/JuliaPolyhedra/Polyhedra.jl/files/7525593/a.txt)

**Comment by blegat** [comment]
Thanks a lot for reporting this! The string interpolation can indeed take quite a large portion of time.
