### ISSUE TITLE
Functions are not defined

### ISSUE THREAD

**Issue by Edenharder** [JuliaPolyhedra/Polyhedra.jl#287]
My environment is:
OS: Archlinux 5.16.5
Julia: 1.7.2
Polyhedra: 0.6.17
CDDLib: 0.7.0

When I test the simple examples in the tutorial
```
julia> using Polyhedra
julia> A = [1 1;1 -1;-1 0]
julia> b = [1,0,0]
julia> hrep = SimpleHRepresentation(A, b)
julia> typeof(hrep)
```
It gives me the error that
```
ERROR: UndefVarError: SimpleHRepresentation not defined
Stacktrace:
 [1] top-level scope
   @ In[1]:3
[2] eval
   @ ./boot.jl:373 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1196
```
Similar error happens with `SimpleVRepresentation`.

**Comment by blegat** [comment]
Which tutorial are you following ? It should now be `h = hrep(A, b)`

**Comment by zpxuxpz** [comment]
@blegat Thank you for the reply. The documentation that I have used is in [this link](https://polyhedra.readthedocs.io/en/latest/representation.html). It's said to be the last version.

**Comment by blegat** [comment]
Thanks, we stopped using readthedocs for a while and should find a way to dismantle it.
