### ISSUE TITLE
Check if a polyhedron in other polyhedron

### ISSUE THREAD

**Issue by XLVII-47** [JuliaPolyhedra/Polyhedra.jl#303]
```julia
A = [1 0 ; 0 1; -1 0; 0 -1 ; -1 -1]
a = [3,3,3,3,3]

p=Polyhedra.polyhedron(hrep(A,a))

##CHECK

p == intersect(p,p)
```

## it must be true but gives false

how to check if a polyhedra is inside another polytope

**Comment by blegat** [comment]
You can do like `issubseth` in https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/304
