### ISSUE TITLE
It eliminated the incorrect variable, didn't it?

### ISSUE THREAD

**Issue by WuSiren** [JuliaPolyhedra/Polyhedra.jl#338]
``` julia
using JuMP, Polyhedra, CDDLib
m = Model()
@variable(m, d[1:2])
@variable(m, 0 <= g[1:2] <= 1)
@constraint(m, d[1] == 1 + 100g[1])
@constraint(m, d[2] == 2 + 100g[2])
all_variables(m) # To check the dimension names.
p = polyhedron(m, CDDLib.Library(:exact))
P = eliminate(p, [3:4;])
[1, 2] in P, [0, 0] in P
```

The result is `(false, true)`, which indicates the projection polyhedron is with respect to the eliminated variable `g[1:2]` but not the expected `d[1:2]`. 

Is this a bug, or I didn't use it correctly?

Looking forward to response. Thanks!

**Comment by schillic** [comment]
@WuSiren there is not yet a new release of this package. For now you can use the development version via the [`dev` command](https://pkgdocs.julialang.org/v1/managing-packages/#developing):
```julia
pkg> dev Polyhedra
```
