### ISSUE TITLE
SimplePolyhedron with AbstractFloat

### ISSUE THREAD

**Issue by blegat** [JuliaPolyhedra/Polyhedra.jl#35]
```julia
using Polyhedra
A = [1 1;1 -1;-1 0]
b = [1,0,0]
plib=getlibraryfor(2, AbstractFloat)
p = polyhedron(SimpleHRepresentation(A, b), plib)
vertices = SimpleVRepresentation(p).V
```
Related https://github.com/QuantEcon/Games.jl/issues/37

**Comment by oyamad** [comment]
Is `SimplePolyhedron` a library already included in `Polyhedra.jl`? (It would be helpful if this is described in the documentation.)

**Comment by blegat** [comment]
Yes, it is already in Polyhedra. It should document it indeed! There are now fallbacks for every operations on polyhedron (e.g. [fallback for double description](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/master/src/doubledescription.jl)) and SimplePolyhedron is just a simple library that implements nothing and thus uses all the fallbacks. Currently, it is slower than CDD, ... but we plan to improve the fallbacks
