### ISSUE TITLE
Improve iterators

### ISSUE THREAD

**Issue by blegat** [JuliaPolyhedra/Polyhedra.jl#44]
Currently, the iterators `vreps`, `hreps`, `points` and `rays` do not return a constant type.
It is not possible to fix it for `vreps` and `hreps` without changing the elements but we can fix if for the other ones. We also need to rename `eqs` and `ineqs` because of #43
Here is what I suggest for the new iterators:

| Iterator | Return type |
|-----------|----------------|
| `equalities` | `AffinePolynomial` |
| `inequalities` | `AffinePolynomial` |
| `halfspaces` | `HalfSpace` |
| `hyperplanes` | `HyperPlane` |
| `points` | `GeometryTypes.Point` or `AbstractArray` |
| `sympoints` | `SymPoint` |
| `rays` | `Ray` |
| `lines` | `Line` |

There would be a function to get the eltype of the iterator, e.g. `pointtype` would return `Point{2, Float63}` or `Vector{Rational{BigInt}}`.
@rdeits @tkoolen What do you think ?

**Comment by rdeits** [comment]
Yeah, that all sounds good. I was looking into this myself, but couldn't figure out where the relevant code is. Where are things like `ineqs()` and `IneqIterator` defined?
