### ISSUE TITLE
New release on METADATA?

### ISSUE THREAD

**Issue by crbinz** [JuliaPolyhedra/Polyhedra.jl#52]
Would be nice to have the latest version registered, since v0.1.2 (latest on METADATA) doesn't seem to work on julia v0.6.

**Comment by blegat** [comment]
Isn't the latest release v0.2.2 ?

**Comment by crbinz** [comment]
Sorry, my mistake, I was looking at the wrong METADATA branch. I'm still curious why `Pkg.update` wasn't giving me v0.2.2, but this issue is moot.
