### ISSUE TITLE
Computing the intersection of 2 or more polytopes

### ISSUE THREAD

**Issue by mforets** [JuliaPolyhedra/Polyhedra.jl#53]
Hi,
Is it possible to use `Polyhedra` to compute the intersection of 2 or more polytopes?
If the answer if "yes", i think it would be nice if it appears in the ["utilities" part of the docs](https://juliapolyhedra.github.io/Polyhedra.jl/latest/utilities.html), and some examples are given -- i volunteer if someone can provide guidance :)

See also: computing intersections in the Polyhedral computation FAQ: https://www.cs.mcgill.ca/~fukuda/soft/polyfaq/node25.html

**Comment by blegat** [comment]
Indeed, that should be there. I have added it in #54 . It is still laking example, you are welcome to add some !

**Comment by mforets** [comment]
great, thanks for your super prompt response! it'll take me some time to read and play with it. then i can propose an example.

**Comment by blegat** [comment]
Thanks a lot ! No hurry of course ;)

**Comment by mforets** [comment]
*(i'll be editing this post with the example)*

We compute the intersection of two randomly generated polygons in V-representation:

```julia
julia> using Polyhedra, CDDLib
julia> P1 = polyhedron(SimpleVRepresentation(randn(15, 2)), CDDLibrary());
julia> P2 = polyhedron(SimpleVRepresentation(randn(15, 2)), CDDLibrary());
julia> Pint = intersect(P1, P2);
```

Notice that the H-representation of the resulting polyhedron has been computed: 

```julia
julia> hashreps(Pint)
true
julia> hasvreps(Pint)
true
julia> npoints(Pint)
9
```

We can plot the polygons and their intersection using `Plots`:

```julia
julia> plot(P1, alpha=0.2, color="blue")
julia> plot!(P2, color="red", alpha=0.2)
julia> plot!(Pint, color="yellow", alpha=0.6)
```

<img width="578" alt="screen shot 2017-11-19 at 23 52 51" src="https://user-images.githubusercontent.com/12424594/32996584-d5908484-cd84-11e7-9153-72bc4ac16181.png">

**Comment by blegat** [comment]
hashreps says whether the polyhedronbis the full space (no constraint) or has inequalities.
You should is hrepiscomputed to check whether the H-representation is computed

**Comment by mforets** [comment]
there is an `examples/` folder with a jupyter notebook. do yo want to have a notebook for this and maybe other examples with figures? 

i like the example of computing the Chebyshev center from Boyd. maybe it would  be nice if we come up with another example that shows the other utility functions.

**Comment by blegat** [comment]
Yes, I think notebooks in the `examples/` folder would be a very nice way to show how to use the different features. In particular, I think that would be the best place to put the example of your previous post.

**Comment by mforets** [comment]
> I think that would be the best place to put the example of your previous post.

done, this is #56
