### ISSUE TITLE
MathProgBase required version

### ISSUE THREAD

**Issue by cc7768** [JuliaPolyhedra/Polyhedra.jl#6]
This line in the REQUIRE file

```
MathProgBase 0.5.10-0.6.0
```

excludes support for `MathProgBase` 0.6.0. Was there a breaking change in this version that prevents `Polyhedra` from using it? Could it just be

```
MathProgBase 0.5.10
```

This will require at least v0.5.10 but allow higher versions as well.

**Comment by blegat** [comment]
Yes, in MPB v0.6.0, the default solver mechanism was moved to JuMP. I will tag a new version of Polyhedra that support MPB v0.6 soon :)

**Comment by cc7768** [comment]
Great! Thanks for the update -- I hadn't realized it made such a big move. Good to know.

Let me know whether there is anything on this side that I can help with to get things plugged in once that PR is merged and tagged.

**Comment by blegat** [comment]
@cc7768 It should be fixed now :)

**Comment by cc7768** [comment]
This is great! Thanks so much for your help.
