### ISSUE TITLE
removehredundancy!(::SimplePolyhedron) doesn't distinguish between Empty and Full Polyhedra

### ISSUE THREAD

**Issue by goretkin** [JuliaPolyhedra/Polyhedra.jl#62]
Is there a way to distinguish between a Polyhedron that contains all the points, and one that contains no points?

As far as I can tell, the representations are currently the same. I'm not sure how one would distinguish the two, except for (and I don't like these) including two halfspaces that don't intersect. Or having 0 points (All polyhedron) vs 1 point (empty polyhedron. Except it does contain 1 point...).

**Comment by blegat** [comment]
Good question. The representations are in fact not the same:

* Empty polyhedron:
    * V-representation : No point, no rays, no nothing :-P
    * H-representation : Something impossible to satisfy, e.g. 0x + 0y = 1.
* Full polyhedron:
    * V-representation : n lines (1, 0, 0), (0, 1, 0), (0, 0, 1), this is used [here](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/67f04cbc28fc29badc8fd7a88869f4478f38ac3f/src/doubledescription.jl#L11). Lines are linear rays which is why `Vlinset` is `IntSet(1:n)`.
    * H-representation : No inequalities, no equalities

**Comment by goretkin** [comment]
Great!! And thanks for the quick response.

So is this a bug in `removehredundancy!(::SimplePolyhedron)`

```julia
julia> empty_v = SimpleVRepresentation(zeros(0,2));

julia> empty_poly = polyhedron(empty_v);

julia> removehredundancy!(empty_poly)
H-representation
linearity 2 1 2
begin
 3 3 real
 0.0 1.0 0.0
 0.0 0.0 1.0
 1.0 -0.0 -0.0
end

julia> collect(hreps(empty_poly))
3-element Array{Polyhedra.HRepElement{2,Float64},1}:
 Polyhedra.HyperPlane{2,Float64}([-1.0, -0.0], 0.0)
 Polyhedra.HyperPlane{2,Float64}([-0.0, -1.0], 0.0)
 Polyhedra.HalfSpace{2,Float64}([0.0, 0.0], 1.0) 

```

I see the insatisfiable, empty halfspace. But also there are also other Hyperplanes that intersect at (x,y) = (0,0).

**Comment by goretkin** [comment]
I remember why I thought the representations were the same:

```julia
square_points = [-1.0 -1.0; -1.0 1.0; 1.0 -1.0; 1.0 1.0]

poly_sq = polyhedron(SimpleVRepresentation(square_points))
poly_sq_right = polyhedron(SimpleVRepresentation(10 .+ square_points))
empty_poly = SimplePolyhedron{2,Float64}(HRepIterator([poly_sq, poly_sq_right]))

julia> collect(hreps(empty_poly))
8-element Array{Polyhedra.HRepElement{2,Float64},1}:
 Polyhedra.HalfSpace{2,Float64}([-0.5, -0.0], 0.5)                 
 Polyhedra.HalfSpace{2,Float64}([-0.0, -0.333333], 0.333333)       
 Polyhedra.HalfSpace{2,Float64}([0.214286, -0.0], 0.214286)        
 Polyhedra.HalfSpace{2,Float64}([-0.0, 0.176471], 0.176471)        
 Polyhedra.HalfSpace{2,Float64}([-0.1, -0.0], -0.9)                
 Polyhedra.HalfSpace{2,Float64}([-0.0, -0.0503067], -0.452761)     
 Polyhedra.HalfSpace{2,Float64}([1.68843e-17, 0.0221349], 0.243484)
 Polyhedra.HalfSpace{2,Float64}([0.0181635, -0.0], 0.199798)       

removehredundancy!(empty_poly)

julia> collect(hreps(empty_poly))
0-element Array{Polyhedra.HRepElement{2,Float64},1}
```

**Comment by blegat** [comment]
Each of your comment shows a bug in `removehredundancy!`, that should be fixed indeed :-P

**Comment by goretkin** [comment]
👍 Good to know!
