### ISSUE TITLE
eltype for some iterators is incorrect

### ISSUE THREAD

**Issue by tkoolen** [JuliaPolyhedra/Polyhedra.jl#7]
```julia
vr = SimpleVRepresentation([1 2; 3 4])

for p in points(vr)
    println(typeof(p))
end
```
prints (as expected):
```julia
Array{Int64,1}
Array{Int64,1}
```

However,
```julia
eltype(points(vr))
```
is `Int64`.

This causes issues with `collect(points(vr))`, for example.

Same for `rays`, possibly others.

Thanks for the great library by the way!

**Comment by blegat** [comment]
Thanks for the feedback. This should be fixed in #11
