### ISSUE TITLE
plot recipe broken

### ISSUE THREAD

**Issue by goretkin** [JuliaPolyhedra/Polyhedra.jl#80]
```julia
square_points = [-1.0 -1.0; -1.0 1.0; 1.0 -1.0; 1.0 1.0]
poly_sq = polyhedron(vrep(square_points))
plot(poly_sq)
```

Due to the interaction between `removevredundancy!` and `points` here https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/b9e6e662e7dd8a5181ddce13b110893d1114e49d/src/recipe.jl#L32

```julia
square_points = [-1.0 -1.0; -1.0 1.0; 1.0 -1.0; 1.0 1.0]
poly_sq = polyhedron(vrep(square_points))
removevredundancy!(poly_sq)
julia> points(poly_sq)
0-element iterator of Array{Float64,1}
```

The solution that would probably work is replacing `points` with `allpoints`, but to be honest I don't understand the reason for having`SymPoint` elements, and why `removevredundancy!` now generates them (as far as I can tell, this is a recent change).

**Comment by blegat** [comment]
Mixing `Point` and `SymPoint` was a bad idea, the plan is to remove `SymPoint` for v0.3.0 and to readd it in v0.4.0 with `SymHalfSpace`, ... but `SymPoint` and `Point` won't be mixed anymore. A V-representation either has only `SymPoint` or it has only `Point`, see https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/75
