### ISSUE TITLE
Iterating over ineqs of a SimpleHRepresentation broken

### ISSUE THREAD

**Issue by tkoolen** [JuliaPolyhedra/Polyhedra.jl#9]
Probably due to a missing `ine.linset` argument in the `nextz` call [here](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/183a8e988f851cd4a08bfc0c6d849fc990aa9e50/src/simplerep.jl#L102)?

**Comment by blegat** [comment]
Indeed, thanks ! That should be fixed in #10

**Comment by tkoolen** [comment]
Thanks for the quick response!
